My_First_Project/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('first_app/',include('first_app.urls')),

]

first_app/urls.py
from django.conf.urls import url
from django.urls import path
from first_app import views


app_name="first_app"

urlpatterns=[
   path('',views.index,name='index'),
   path('test/',views.contact,name='contact'),
   path('form/',views.form,name='form')
]

first_app/models.py
from django.db import models

# Create your models here.



class Musician(models.Model):
    #id=models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument=models.CharField(max_length=100)


    def __str__(self):
        return self.first_name+" "+self.last_name;


class Album(models.Model):
    artist = models.ForeignKey(Musician,on_delete=models.CASCADE)
    name= models.CharField(max_length=100)
    release_date=models.DateField()

    ratting=(

    (1,"worst"),
    (2,"Bad"),
    (3,"Not Bad"),
    (4,"Good"),
    (5,"Excellent"),


    )
    num_stars=models.IntegerField(choices=ratting)


    def __str__(self):
        return self.name

first_app/forms.py
from django import forms
from first_app import models

class MusicianForm(forms.ModelForm):
    class Meta:
        model =models.Musician
        fields = ['first_name']
        #exclude=['last_name']
        #fields="__all__"

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Musician,Album
from first_app import forms

# Create your views here.

def index(request):
    musician_list=Musician.objects.order_by('first_name');

    diction={'text1':'i am a text sent from diction',
    'musician' : musician_list,'sample_date' : Album.objects.get(pk=1)}
    return render(request,'first_app/index.html',context=diction);

def contact(request):
    return HttpResponse("<h1>contact</h1>")

def about(request):
    return HttpResponse("<h1>About</h1> <a href='/contact/'>Contact</a>  <a href='/'>Home</a>");

def form(request):
    new_form=forms.MusicianForm()



    if request.method=='POST':
        new_form = forms.MusicianForm(request.POST)


        if new_form.is_valid():
            new_form.save(commit=True)
            return index(request)
    diction={'test_form' : new_form,'heading_1': 'Add New Musician'}

    return render(request,'first_app/form.html',context=diction);

templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <meta charset="utf-8">
    <title>Form</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'first_app:index' %}">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'first_app:form' %}">Form</a>
    </li>
  </ul>
</nav>

  <div class="container">

    {% block body_block %}


      {% endblock %}

    </div>


  </body>

templates/first_app/form.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}


    <h3>{{heading_1}}  </h3>

  <a href="{% url 'first_app:index' %}">Back</a>

   <form action="" method='POST'>

     {{test_form.as_p}}

     {% csrf_token %}

     <input type='submit' name='submit' value='Submit'>


     <form/>

     <hr>

     {% if form_submited %}


      <p>Field : {{field}}</p>

      {% endif %}



{% endblock %}

templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load static  %}
{% load my_filters %}
{% block body_block %}

    <h1>{{text1}}  </h1>

<h2>{{"ok"|custom_filter:"New Addition"}}</h2>

    <a href="{% url 'first_app:form' %}">Add new</a>

    <table border="1">

      <tr>

        <th>First Name</th>
        <th>Last Name</th>
        <th>Instrument</th>


       {% for row in musician%}

       <tr>

         <td>{{row.first_name | add:" Mr"}}</td>
          <td>{{row.last_name}}</td>
           <td>{{row.instrument}}</td>


      </tr>

      {% endfor %}

    </table>

      <img src="{% static 'images/fahimPic.jpg'%}">


{% endblock %}